name: link_life
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.6
  qr_flutter: ^4.1.0
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.1.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/blood.png
